"""Update review model

Revision ID: 086c342d9a41
Revises: 0bcec92a5d42
Create Date: 2023-09-28 11:54:09.549133

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "086c342d9a41"
down_revision: Union[str, None] = "0bcec92a5d42"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reviews", sa.Column("food_rating", sa.Integer(), nullable=True))
    op.add_column("reviews", sa.Column("service_rating", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("reviews", "service_rating")
    op.drop_column("reviews", "food_rating")
    # ### end Alembic commands ###
