"""Add autoincrement review

Revision ID: 0bcec92a5d42
Revises: 63c093fd439a
Create Date: 2023-09-28 08:53:51.114504

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0bcec92a5d42"
down_revision: Union[str, None] = "63c093fd439a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
