"""update user model

Revision ID: 30fb493e6cd0
Revises:
Create Date: 2023-09-21 15:55:54.368520

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "30fb493e6cd0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("registration_date", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("last_order_date", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_order_date")
    op.drop_column("users", "registration_date")
    # ### end Alembic commands ###
